### ISSUE TITLE
Non Nodejs Programs

### ISSUE THREAD

**Issue by ramiroaisen** [theMackabu/pmc#2]
I would be nice to have support for non-nodejs programs. It would be really nice to run rust programs directly.

Maybe we can add an [interpreter] config that the user need to specify instead of defaulting to node.

**Comment by theMackabu** [comment]
https://github.com/theMackabu/pmc/blob/ab2aa70ad14fae88e74c08e83462b5ea200a2b7a/src/cli/mod.rs#L100-L106 already added, non nodejs programs run under the specified shell in `config.toml`
