### ISSUE TITLE
Systemd unit file creation and pmc resurrect

### ISSUE THREAD

**Issue by ramiroaisen** [theMackabu/pmc#3]
It would be really nice to have Systemd unit file creatiion like pm2 has.
It would also necesary to support `pmc resurrect` and a `~/.pmc` folder to store the process list.

**Comment by theMackabu** [comment]
`pmc resurrect` is a work in progress, `~/.pmc/process.dump` already exists and stores the current process list. Ill look into systemd unit file creation.
