### ISSUE TITLE
Enable process management by Name

### ISSUE THREAD

**Issue by wHoIsDReAmer** [theMackabu/pmc#4]
**Description:**
Currently pmc can only manage processes by their Ids. This limitation makes it difficult to interact with processes in a more intuitive and user-friendly manner. Adding the ability to manage processes by both Id and Name would greatly enhance usability.

**Proposal:**

Implement functionality to allow pmc to identify and manage processes using both their Ids and Names. This would enable users to perform actions such as restarting, stopping, and monitoring processes by referring to their names in addition to their Ids.

**Advantages:**
* Improved user experience and flexibility
* Easier identification and management of processes
* Consistency with tools like pm2 which support process management by name

**Comment by theMackabu** [comment]
I have implemented this for start, create, and stop in https://github.com/theMackabu/pmc/commit/03eb936444d430e6fcfbc238b51959ffd1387f5d

I will implement other cli actions soon
