### ISSUE TITLE
v2.0.0 fails to run programs

### ISSUE THREAD

**Issue by PierrickGT** [theMackabu/pmc#9]
I've updated to the latest 2.0.0 version but I can't run any programs anymore.

Here is the error I have in logs:
```
[PMC] (cc) Unable to execute the command
execvp: No such file or directory
```

It's working perfectly fine on version 1.9.0
pmc is running on an ARMv8 architecture.

**Comment by theMackabu** [comment]
Should have force updated $HOME/.pmc/config.toml as the shell now uses absolute paths, sorry about that. The fix should be setting "bash" to "/bin/bash"

**Comment by PierrickGT** [comment]
Thanks for the prompt answer.
I've modified `bash` to `/bin/bash` in `$HOME/.pmc/config.toml` and now it works.

Thank you for your work! Awesome tool.

**Comment by theMackabu** [comment]
https://github.com/theMackabu/pmc/commit/ccea28ea3feb10ec2eaaa23b82def71772efcd1c added a warning with this commit
